services:
  # ----------- Base de datos (contenedor de datos) -----------
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  # ----------- Gateway -----------
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG:-HS256}
      JWT_TTL_SECONDS: ${JWT_TTL_SECONDS:-3600}
      USER_SVC: http://user-service:8000
      TRACKER_SVC: http://tracker-service:8000
    depends_on:
      - auth-service
      - user-service
      - catalog-service
      - goals-service
      - stats-service
      - tracker-service
    ports:
      - "8000:8000"
    networks:
      - backend

  # ----------- Microservicios -----------

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG:-HS256}
      JWT_TTL_SECONDS: ${JWT_TTL_SECONDS:-3600}
      USER_SVC: http://user-service:8000
    depends_on:
      - db
    networks:
      - backend

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - backend

  catalog-service:
    build:
      context: ./services/catalog-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - backend

  goals-service:
    build:
      context: ./services/goals-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - backend

  stats-service:
    build:
      context: ./services/stats-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TRACKER_SVC: http://tracker-service:8000
    depends_on:
      - db
    networks:
      - backend

  tracker-service:
    build:
      context: ./services/tracker-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - backend

# ----------- Volúmenes -----------
volumes:
  db_data:

# ----------- Redes -----------
networks:
  backend:
    driver: bridge
